var res = {
	loading_image: "res/buttons/load.png",
	btn_prev_anim: "res/buttons/previous_animation_button@2x.png",
	btn_prev_anim_s: "res/buttons/previous_animation_button_pressed@2x.png",
	btn_prev_frame: "res/buttons/previous_frame_button@2x.png",
	btn_prev_frame_s: "res/buttons/previous_frame_button_pressed@2x.png",
	btn_play: "res/buttons/play_button@2x.png",
	btn_play_s: "res/buttons/play_button_pressed@2x.png",
	btn_pause: "res/buttons/pause_button@2x.png",
	btn_pause_s: "res/buttons/pause_button_pressed@2x.png",
	btn_next_frame: "res/buttons/next_frame_button@2x.png",
	btn_next_frame_s: "res/buttons/next_frame_button_pressed@2x.png",
	btn_next_anim: "res/buttons/next_animation_button@2x.png",
	btn_next_anim_s: "res/buttons/next_animation_button_pressed@2x.png",
	btn_restart: "res/buttons/restart_button@2x.png",
	btn_restart_s: "res/buttons/restart_button_pressed@2x.png",
	btn_bg: "res/buttons/white_bg_button@2x.png",
	btn_bg_s: "res/buttons/white_bg_button_pressed@2x.png",
	btn_next_seq: "res/buttons/right_arrow@2x.png",
	btn_next_seq_s: "res/buttons/right_arrow_pressed@2x.png",
	btn_prev_seq: "res/buttons/left_arrow@2x.png",
	btn_prev_seq_s: "res/buttons/left_arrow_pressed@2x.png",
	gaf_logo: "res/buttons/gaf_logo@2x.png"
};

var g_resources = [
	"res/biggreen/biggreen1.png",
	"res/biggreen/biggreen2.png",
	"res/bird_bezneba/bird_bezneba1.png",
	"res/bird_bezneba/bird_bezneba2.png",
	"res/bird_bezneba/bird_bezneba3.png",
	"res/bird_bezneba/bird_bezneba4.png",
	"res/bird_bezneba/bird_bezneba5.png",
	"res/bird_bezneba/bird_bezneba6.png",
	"res/christmas2013_julia2/christmas2013_julia21.png",
	"res/christmas2013_julia2/christmas2013_julia22.png",
	"res/cut_the_hope/cut_the_hope1.png",
	"res/cut_the_hope/cut_the_hope2.png",
	"res/cut_the_hope/cut_the_hope3.png",
	"res/cut_the_hope/cut_the_hope4.png",
	"res/cut_the_hope/cut_the_hope5.png",
	"res/cut_the_hope/cut_the_hope6.png",
	"res/fairy2/fairy21.png",
	"res/fairy2/fairy22.png",
	"res/fairy2/fairy23.png",
	"res/fairy2/fairy24.png",
	"res/fireman/fireman.png",
	"res/fireman/fireman_2.png",
	"res/impiretank_05_oneplace/impiretank_05_oneplace1.png",
	"res/impiretank_05_oneplace/impiretank_05_oneplace2.png",
	"res/myshopsgame4/myshopsgame41.png",
	"res/myshopsgame4/myshopsgame42.png",
	"res/peacock_feb3_natasha/peacock_feb3_natasha1.png",
	"res/peacock_feb3_natasha/peacock_feb3_natasha2.png",
	"res/tiger/tiger1.png",
	"res/tiger/tiger2.png",
	"res/sounds_example_tank/sounds_example_tank.png",
	"res/sounds_example_tank/sounds_example_tank_2.png",
	"res/sounds_example_tank/sounds_example_tank_sound21.mp3",
	"res/sounds_example_tank/sounds_example_tank_sound39.mp3",
	"res/dynamic_textfields/text_field_demo.png",
	"res/dynamic_textfields/text_field_demo_2.png",
	"res/dynamic_textfields/Cooper Black.ttf"
];
for (var i in res) {
    g_resources.push(res[i]);
}
